services:
  taskpilot-blob-storage:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    container_name: taskpilotst-blob-storage
    ports:
      - "10000:10000"
    volumes:
      - ./.containers/blob_storage/data:/data
    command: "azurite-blob --blobHost 0.0.0.0 -l /data --skipApiVersionCheck"